### ISSUE TITLE
Being implementing `challenge` and `claim` methods on the `SmartContractWallet`

### ISSUE THREAD

**Issue by geoknee** [statechannels/nitro-smart-contract-wallet#3]
- If either party wants to end the relationship, they:
    - stop transacting off chain
    1.  call `challenge`.
    2. (optional) the other party calls `challenge()` with a later state
    3. `providePreimage()`
    4. someone calls `claim()`. the intermediary is ejected with their money.
- `challenge(state)`
    - set contract.Status == Challenge
    - start timeout
    - owner and intermediary have opportunity to set latest `TurnNumber`. fingerprint
    - after timeout expires, move status to `Finalized`
- `claim()`
    - require `status == Finalized`
    - loop over any remaining HTLCs, compute `moneyFromHTLCForMe`, `moneyFromHTLCForThem`
    - compute `netPayout = state.intermediaryBalance + moneyFromHTLCForThem - moneyFromHTLCForMe`
    - execute payout
    - set intermediary = 0

**Comment by lalexgap** [comment]
This functionality has been implemented but only lightly tested. I'll create a separate issue for testing.
